default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: recipe_manager_api_development
test:
  <<: *default
  database: recipe_manager_api_test
production:
  <<: *default
  database: recipe_manager_api_production
  username: recipe_manager_api
  password: <%= ENV['RECIPE_MANAGER_API_DATABASE_PASSWORD'] %>
